site_name: Pre Fab Academy

theme:
  name: material 

  features:
    - header.autohide
    
  palette:
    primary: cyan

  features:
      - navigation.tracking

  features:
        - navigation.tabs
        - navigation.tabs.sticky

 icon:
    admonition:
      <type>: <icon>


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


nav:
  - Home: index.md
  - About: about.md
  - Assignments:
    - Week-1: week1.md
    - Week-2: week2.md
    - Week-3: week3.md
    - Week-4: week4.md

use_directory_urls: false
