site_name: Pre Fab Academy

theme:
  name: material 
  features:
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

  logo: LogoIcelandic_WhitemoreSpace.svg
  favicon: LogoIcelandic_GreenMoreSpace.svg

  palette:
    primary: indigo
    accent: cyan
   
  features:
      - navigation.tracking


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


nav:
  - Home: index.md
  - About: about.md
  - Assignments:
    - Creating a website: Website.md
    - Designing, producing and programming a circuit: Circuit.md
    - ShopBot: ShopBot.md
    - Computer aided design: ComputerAidedDesign.md
    - Final project: FinalProject.md

use_directory_urls: false
