site_name: Pre Fab Academy

theme:
  name: material 

  features:
    - header.autohide
    
  palette:
    primary: cyan

  features:
      - navigation.tracking

  features:
        - navigation.tabs
        - navigation.tabs.sticky
        

nav:
  - Home: index.md
  - About:
    - Bio: about-me/about.md
  - Assignments:
    - Week-1: Assignments/week1.md
    - Week-2: Assignments/week2.md
    - Week-3: Assignments/week3.md
    - Week-4: Assignments/week4.md

use_directory_urls: false
