site_name: Pre Fab Academy

theme:
  name: material 

  features:
    - header.autohide
    
  palette:
    primary: cyan

  features:
      - navigation.tracking

  features:
        - navigation.tabs
        - navigation.tabs.sticky
        